---
- name: playbook tomcat setup
  hosts: webservers
  become: yes
  tasks:
    - name: Create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: Create tomcat user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /bin/false  # Security best practice: no login shell
        system: yes
        state: present
	
    - name: Install Apache Tomcat package
      ansible.builtin.yum: 
        name: tomcat
        state: present
		
    - name: Start Tomcat service
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes
